# Generated by Django 4.2.7 on 2023-11-27 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0005_insertcrypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_type', models.CharField(choices=[('0', 'Rial'), ('1', 'BTC'), ('2', 'USDT'), ('3', 'ETH')], max_length=1)),
                ('mount', models.FloatField()),
                ('fee', models.FloatField()),
                ('trx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_wallet_addr', models.CharField(max_length=255)),
                ('admin_wallet_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('user_description', models.TextField(blank=True, null=True)),
                ('admin_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Valid'), ('1', 'Pending'), ('2', 'Failed')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_cryptos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
